import Navbar from '@/Components/navbar/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'
import Footer from '@/Components/footer/Footer'
import { ThemeProvider } from './Context/ThemeContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider>
        <div className="container">
       <Navbar/>
        {children}
        <Footer/>
        </div>
        </ThemeProvider>
        </body>
    </html>
  )
}
